### ISSUE TITLE
Add an easy way to inject mock data into symfony container services ?

### ISSUE THREAD

**Issue by yoanm** [yoanm/Behat3SymfonyExtension#32]
- Add a `MockManager` component + `MockManagerAwareInterface`
 -  `MockManager` will provide a method to store data in a list for a given mock id (for instance `third_party_client`), and will call the method and service configured (`app.client.third_party` and `setFakeDataList`) with an array of data when a BeforeRequestEvent is dispatched
 - Configuration could be : 
```yaml
default:
  extensions:
    Yoanm\Behat3SymfonyExtension:
      extensionConfig:
        mock:
         third_party_client: # <-- mock identifier
           service_id: app.client.third_party # <-- symfony app service id. (should  be mocked)
           method: setFakeDataList # <-- method to call on the service to inject data
```
